
input CreateDeliveryPersonInput {
  cpf: String!
  email: String!
  licensePlate: String
  name: String!
  phone: String!
  vehicleType: VehicleType!
}

scalar DateTime

type DeliveryPerson {
  cpf: String!
  createdAt: DateTime!
  currentLatitude: Float
  currentLongitude: Float
  email: String!
  id: Int!
  isActive: Boolean!
  joinedAt: DateTime!
  lastLocationUpdate: DateTime
  licensePlate: String
  name: String!
  phone: String!
  rating: Float!
  status: DeliveryPersonStatus!
  totalDeliveries: Int!
  updatedAt: DateTime!
  vehicleType: VehicleType!
}

enum DeliveryPersonStatus {
  AVAILABLE
  BUSY
  OFFLINE
  ON_BREAK
}

type Mutation {
  activateDeliveryPerson(id: Int!): DeliveryPerson!
  createDeliveryPerson(createDeliveryPersonInput: CreateDeliveryPersonInput!): DeliveryPerson!

  deactivateDeliveryPerson(id: Int!): DeliveryPerson!

  removeDeliveryPerson(id: Int!): DeliveryPerson!
  updateDeliveryPerson(id: Int!, updateDeliveryPersonInput: UpdateDeliveryPersonInput!): DeliveryPerson!
  updateDeliveryPersonLocation(updateLocationInput: UpdateLocationInput!): DeliveryPerson!
  updateDeliveryPersonStatus(updateStatusInput: UpdateStatusInput!): DeliveryPerson!
}

type Query {
  availableDeliveryPersonsNearby(latitude: Float!, longitude: Float!, radiusKm: Float!): [DeliveryPerson!]!
  deliveryPerson(id: Int!): DeliveryPerson!
  deliveryPersons(isActive: Boolean, status: String): [DeliveryPerson!]!
}

input UpdateDeliveryPersonInput {
  cpf: String
  email: String
  licensePlate: String
  name: String
  phone: String
  vehicleType: VehicleType
}

input UpdateLocationInput {
  accuracy: Float
  deliveryPersonId: Int!
  heading: Float
  latitude: Float!
  longitude: Float!
  speed: Float
}

input UpdateStatusInput {
  deliveryPersonId: Int!
  status: String!
}

enum VehicleType {
  BIKE
  CAR
  MOTORCYCLE
  SCOOTER
  WALKING
}